{% set name = "fermitools" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/Sciencetools.git
  git_rev: a981afe1cbcf2f1e29b6bd8aa84481243840258c

build:
  number: 0
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - openmp  # [linux]
    - llvm-openmp  # [osx]

  host:
    - clhep
    - cfitsio
    - cppunit
    - f2c
    - fftw
    - gsl
    - healpix_cxx 3.31
    - minuit2
    - pmw
    - python 3.9.*
    - readline
    - swig
    - wcslib
    - xerces-c

  run:
    - clhep
    - cfitsio
    - cppunit
    - f2c
    - fftw
    - gsl
    - healpix_cxx 3.31.*
    - pmw
    - python 3.9.*
    - readline
    - swig
    - wcslib
    - xerces-c

  # host:
  #   - python 3.9.* 


test:
 imports:
   - py_facilities
   - pyLikelihood
   - UnbinnedAnalysis

  # commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
