{% set name = "fermitools" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/Sciencetools.git
  git_rev: cmake-update
  # path: ../../ScienceTools

build:
  number: 0
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - openmp  # [linux]
    - llvm-openmp  # [osx]

  host:
    - cfitsio
    - clhep
    - cmake >=3.18
    - cppunit
    - f2c 0.0.2.*
    - fftw
    - gsl
    - healpix_cxx 3.31.*
    - minuit2_standalone
    # - pmw
    - pkg-config
    - python 3.9.*
    - readline
    - swig
    - wcslib
    - xerces-c

  run:
    - cfitsio
    - clhep
    - cppunit
    - f2c 0.0.2.*
    - fermitools-data
    - fftw
    - gsl
    - healpix_cxx 3.31.*
    - minuit2_standalone
    - readline
    - wcslib
    - xerces-c

    #### Python Libraries ####
    - astropy
    - matplotlib
    - numpy
    - pmw
    - python 3.9.*
    - pyyaml


test:
  imports:
    - py_facilities
    - pyLikelihood
    - UnbinnedAnalysis

  requires:
    - fermitools-test-scripts-data
    - junit-xml

  files:
    - tests/ST-unit-test

  commands:
    - tests/ST-unit-test -w
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
