language: generic

matrix:
  include:
    - env: CONFIG=linux_aarch64_ UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  # - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi
