{% set name = "fermitools" %}
{% set version = "2.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/Fermitools-conda.git
  git_rev: root_free

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }} 7.5.*    # [linux]
    - {{ compiler('cxx') }} 7.5.*  # [linux]
    - {{ compiler('c') }}          # [osx]
    - {{ compiler('cxx') }}        # [osx]

  host:
    - ape >=3
    - aplpy
    - astropy <4
    - blas
    - clhep 2.4.4.*
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.17
    - openblas
    - pmw
    - python >=3.7
    - readline
    - scons 3.0.3.*
    - swig
    - wcslib 5.*
    - xerces-c
    - zstd 

  run:
    - ape >=3
    - aplpy
    - astropy <4
    - blas
    - clhep 2.4.4.*
    - cppunit
    - f2c 0.0.2
    - fftw
    - gsl
    - healpix_cxx
    - matplotlib
    - ncurses
    - numpy  >=1.17
    - openblas
    - pmw
    - python 3.7.*
    - pyyaml
    - readline
    - scipy
    - wcslib 5.*
    - xerces-c
    - zstd 

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
