{% set name = "fermitools" %}
{% set version = "1.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/Fermitools-conda.git
  git_rev: py3_extensive_tagging

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }} 7.5.*    # [linux]
    - {{ compiler('cxx') }} 7.5.*  # [linux]
    - {{ compiler('c') }}          # [osx]
    - {{ compiler('cxx') }}        # [osx]

  host:
    - fermitools-build-deps {{ version }}

  run:
    - fermitools-dependencies {{ version }}

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
