{% set name = "fermitools" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/Fermitools-conda.git
  git_rev: python27

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  build:
    - {{ compiler('c') }} 7.5.*     # [linux]
    - {{ compiler('cxx') }} 7.5.*   # [linux]
    - {{ compiler('c') }} 9.*       # [osx]
    - {{ compiler('cxx') }} 9.*     # [osx]

  host:
    - fermitools-build-deps {{ version }}

  run:
    - fermitools-dependencies {{ version }}

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
